### PR TITLE
Add control flow page

### LINKED ISSUE #38: Missing For and If constructs
The site documentation seems to be missing the constructs for `<For>` and `<If>` (soon to be replaced by new syntax).

### PR DESCRIPTION
**Pull request by totaltrash**
Fixes #38

### CODE REVIEW

**Review by miguel-s — APPROVED** [review]
Thanks for the PR! ❤️

**Comment by msaraiva** [comment]
Hi @totaltrash!

Thanks for the PR. 

As we're getting close to release `v0.5`, I'm not sure it's worth to document `<For>` and `<If>`, specially because they will be already deprecated in `v0.5` and later removed in `v0.6`. However, since the syntax is getting more powerful, it would be nice to have a dedicated page for it, where users could jump directly into it whenever in doubt about any aspect of the syntax. Something similar to https://svelte.dev/docs#Template_syntax.

So my suggestion would be to take this opportunity to start working on this new page. We could rename  `Control Flow` to `Template Syntax` and replace the your examples with their new counterparts.

You can start with just `{#for}` and `{#if}` as originally intended and later, if you feel in the mood, you can add more stuff. WDYT?

Just in case you're not sure how the the new syntax looks like, here's an example for each one of them:

### for/else



```
<For each={{item <- @items}}>
  Item: {{item}}
</For>
<If condition={{@items == []}}>
  No items
</If>

<!-- new syntax -->

{#for item <- @items}
  Item: {item}
{#else}
  No items
{/for}
```

---

### if/elseif/else

```
{#if @value == 0}
  <div class="equal">
    Value {@value} is 0
  </div>
{#elseif @value > 0}
  <div class="greater">
    Value {@value} is greater than 0
  </div>
{#else}
  <div class="lower">
    Value {@value} is lower than 0
  </div>
{/if}
```

**Comment by totaltrash** [comment]
Yes, will do, that sounds like a good idea. I wasn't sure how far off the new syntax was from being released.

**Comment by totaltrash** [comment]
I've updated the page as suggested

**Comment by msaraiva** [comment]
@totaltrash thanks!

**Pull request merged**
